package com.example.twitchapp.database

object DbConstants {
    const val STREAMS_TABLE_NAME = "STREAMS"
    const val GAMES_TABLE_NAME = "GAMES"
    const val TWITCH_NOTIFICATIONS_TABLE_NAME = "NOTIFICATIONS_PIVOT"
    const val GAME_NOTIFICATIONS_TABLE_NAME = "GAME_NOTIFICATIONS"
    const val STREAM_NOTIFICATIONS_TABLE_NAME = "STREAMS_NOTIFICATIONS"
}
const val GAME_STREAMS_PAGE_SIZE = 20